export async function executeJulesCommand(endpoint: string, apiKey: string, commandJson: string): Promise<string> {
  if (!endpoint) {
    throw new Error("Agent endpoint is not configured. Please set it in Settings.");
  }

  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  if (apiKey) {
    headers['Authorization'] = `Bearer ${apiKey}`;
  }

  try {
    // Parse the JSON command generated by Gemini, stripping markdown if present
    const cleanJson = commandJson.replace(/```json/gi, '').replace(/```/g, '').trim();
    const payload = JSON.parse(cleanJson);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      throw new Error(errData.error || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.result;
  } catch (error: any) {
    throw new Error(`Agent Error: ${error.message}`);
  }
}
